### ISSUE TITLE
static file

### ISSUE THREAD

**Issue by shabane** [gethugothemes/bookworm-light#11]
how we can add a static file to a md

```bash
![example image](/images/post/example.jpg)
```

this dosen't work

**Comment by tfsomrat** [comment]
Hey @shabane 

We are using Hugo Pipe to process all the images for faster rendering. that's why you need to call a shortcode to display an image.  All the shortcodes are available on the elements page. check it out.

```
{{< image src="images/post/01.jpg" >}}
```

but if you still want to call an image like MD format, then you need to place this image in the `static` folder, instead of the `assets` folder.  thank you

**Comment by shabane** [comment]
hi, thank you for your answer. it's worked well now.
many many thank you

**Comment by tfsomrat** [comment]
Thanks for your feedback @shabane , Hope you like our theme. A star to the repository would be much appreciated.
