### ISSUE TITLE
Error in style.scss

### ISSUE THREAD

**Issue by nataliepjlin** [gethugothemes/bookworm-light#14]
Hi guys, I recently added the whole package to my file. When using the command `hugo server`, it will display `Invalid CSS` in `style.scss`.  I'm not sure that whether `[params.variables]` should be replace with `[params]` or something else.
Thanks a lot!!!
CODE:

> //site variables
> [params.variables]
> $font-primary: sans-serif;
> 
> $h1: 48px;
> $h1-lg: 52px;
> $h1-md: 44px;
> $h2: 40px;
> $h2-md: 36px;
> $h3: 32px;
> $h3-md: 28px;
> $h4: 24px;
> $h5: 20px;
> $h6: 16px;`

**Comment by mehedi-sharif** [comment]
Hello @nataliepjlin 

Thanks for choosing this theme, you probably set up this theme incorrectly. please follow the documentation of this theme. or you can run this theme after pulling it on your local machine by this command `cd exampleSite && hugo server --themesDir ../..`

**Comment by nataliepjlin** [comment]
@mehedi-sharif it works! thank you so much:)

**Comment by nataliepjlin** [comment]
hi @mehedi-sharif 
The command works! however, I have no idea about how I can move the `config.toml` file to my own project. When I copy it to my own project, it can't reach  `images/logo` nor other images. Is there any tutorials or ways to solve it?
Another issue I have is that I upload it to forestry and deploy on netifly, but [the site](https://nataliepjlin.netlify.app/) I built can't display images either...

**Comment by mehedi-sharif** [comment]
Hello there,

I have a quick tip for you, don't move the config file into your project, rather than move your site into this theme, it will be easier for you. also you need to put all the images in the assets folder, otherwise, it will not work. and for forestry and netlify, please follow those steps https://github.com/gethugothemes/bookworm-light#content-management-system
